---
title: "Covariance Plots Per Errorsd"
format:
  html:
    toc: true
    toc-depth: 4
    toc-expand: true
    toc-location: left
---

```{r, include=F, echo=F, message=F, warning=F}
library(tidyverse)
library(tidyquant)
library(ggdist)
library(ggthemes)
library(readr)
```

```{r, include=F, echo=F, message=F, warning=F}
dat <- read_csv("sim_results/sim_results_2026-02-10_fixed.csv")
```

## $Log_{10} \text{ } pBF_{ic}$
### $Log_{10} \text{ } pBF_{ic}$, es = 0.1, k = 2, covariance
```{r, warning=F, echo = F}
# log pbf IC - covariance
# es = 0.1

# New facet label names for k variable
k.labs <- c("k = 2", "k = 3", "k = 10")
names(k.labs) <- c("2", "3", "10")

# New facet label names for n variable
n.labs <- c("n = 20", "n = 80", "n = 200", "n = 500")
names(n.labs) <- c("20", "80", "200", "500")

# New facet label names for error variable
errorsd.labs <- c("errorsd = 0", "errorsd = 0.5", "errorsd = 0.8")
names(errorsd.labs) <- c("0", "0.5", "0.8")

dat %>%
  filter(es == 0.1, k == 2) %>%
  ggplot(aes(x = log10(prodbf_cov_ic), y = factor(n), fill = factor(errorsd))) +
  stat_halfeye(
    adjust = 0.5,
    justification = -0.4,
    .width = 0,
    point_colour = NA, 
    alpha = 0.5
  ) +
  stat_dots(
    side = "left",
    justification = 1.3,
    binwidth = 0.1, 
    alpha=0.05, 
  ) +
  facet_wrap(~ factor(errorsd) , labeller = labeller(errorsd = errorsd.labs)) + 
   geom_vline(xintercept=log10(1), 
              color = "red", 
              size = 0.05) + 
   labs(x = expression(log[10](prodbf_cov_ic)), 
       y = "Number of Studies (k)", 
       title = "log prodbf_cov_ic (es = 0.1, k = 2, Hi is false), covariance",
       subtitle = "Sample Size (n), Number of Studies (k) and Reliability (errorsd)",
       caption = "Red line: log(1) = 0, 1000 iterations", fill = "Error SD") +  
  theme_minimal()
```
### $Log_{10} \text{ } pBF_{ic}$, es = 0.1, k = 3, covariance
```{r, warning=F, echo = F}
# log pbf IC - covariance
# es = 0.1

# New facet label names for k variable
k.labs <- c("k = 2", "k = 3", "k = 10")
names(k.labs) <- c("2", "3", "10")

# New facet label names for n variable
n.labs <- c("n = 20", "n = 80", "n = 200", "n = 500")
names(n.labs) <- c("20", "80", "200", "500")

# New facet label names for error variable
errorsd.labs <- c("errorsd = 0", "errorsd = 0.5", "errorsd = 0.8")
names(errorsd.labs) <- c("0", "0.5", "0.8")

dat %>%
  filter(es == 0.1, k == 3) %>%
  ggplot(aes(x = log10(prodbf_cov_ic), y = factor(n), fill = factor(errorsd))) +
  stat_halfeye(
    adjust = 0.5,
    justification = -0.4,
    .width = 0,
    point_colour = NA, 
    alpha = 0.5
  ) +
  stat_dots(
    side = "left",
    justification = 1.3,
    binwidth = 0.1, 
    alpha=0.05, 
  ) +
  facet_wrap(~ factor(errorsd) , labeller = labeller(errorsd = errorsd.labs)) + 
   geom_vline(xintercept=log10(1), 
              color = "red", 
              size = 0.05) + 
   labs(x = expression(log[10](prodbf_cov_ic)), 
       y = "Number of Studies (k)", 
       title = "log prodbf_cov_ic (es = 0.1, k = 3, Hi is false), covariance",
       subtitle = "Sample Size (n), Number of Studies (k) and Reliability (errorsd)",
       caption = "Red line: log(1) = 0, 1000 iterations", fill = "Error SD") +  
  theme_minimal()
```

### $Log_{10} \text{ } pBF_{ic}$, es = 0.1, k = 10, covariance
```{r, warning=F, echo = F}
# log pbf IC - covariance
# es = 0.1

# New facet label names for k variable
k.labs <- c("k = 2", "k = 3", "k = 10")
names(k.labs) <- c("2", "3", "10")

# New facet label names for n variable
n.labs <- c("n = 20", "n = 80", "n = 200", "n = 500")
names(n.labs) <- c("20", "80", "200", "500")

# New facet label names for error variable
errorsd.labs <- c("errorsd = 0", "errorsd = 0.5", "errorsd = 0.8")
names(errorsd.labs) <- c("0", "0.5", "0.8")

dat %>%
  filter(es == 0.1, k == 10) %>%
  ggplot(aes(x = log10(prodbf_cov_ic), y = factor(n), fill = factor(errorsd))) +
  stat_halfeye(
    adjust = 0.5,
    justification = -0.4,
    .width = 0,
    point_colour = NA, 
    alpha = 0.5
  ) +
  stat_dots(
    side = "left",
    justification = 1.3,
    binwidth = 0.1, 
    alpha=0.05, 
  ) +
  facet_wrap(~ factor(errorsd) , labeller = labeller(errorsd = errorsd.labs)) + 
   geom_vline(xintercept=log10(1), 
              color = "red", 
              size = 0.05) + 
   labs(x = expression(log[10](prodbf_cov_ic)), 
       y = "Number of Studies (k)", 
       title = "log prodbf_cov_ic (es = 0.1, k = 10, Hi is false), covariance",
       subtitle = "Sample Size (n), Number of Studies (k) and Reliability (errorsd)",
       caption = "Red line: log(1) = 0, 1000 iterations", fill = "Error SD") +  
  theme_minimal()
```

## $Log_{10} \text{ } pBF_{iu}$
### $Log_{10} \text{ } pBF_{iu}$, es = 0.1, k = 2, covariance
```{r, warning=F, echo = F}
# log pbf IU - covariance
# es = 0.1

# New facet label names for k variable
k.labs <- c("k = 2", "k = 3", "k = 10")
names(k.labs) <- c("2", "3", "10")

# New facet label names for n variable
n.labs <- c("n = 20", "n = 80", "n = 200", "n = 500")
names(n.labs) <- c("20", "80", "200", "500")

# New facet label names for error variable
errorsd.labs <- c("errorsd = 0", "errorsd = 0.5", "errorsd = 0.8")
names(errorsd.labs) <- c("0", "0.5", "0.8")

dat %>%
  filter(es == 0.1, k == 2) %>%
  ggplot(aes(x = log10(prodbf_cov_iu), y = factor(n), fill = factor(errorsd))) +
  stat_halfeye(
    adjust = 0.5,
    justification = -0.4,
    .width = 0,
    point_colour = NA, 
    alpha = 0.5
  ) +
  stat_dots(
    side = "left",
    justification = 1.3,
    binwidth = 0.1, 
    alpha=0.05, 
  ) +
  facet_wrap(~ factor(errorsd) , labeller = labeller(errorsd = errorsd.labs)) + 
   geom_vline(xintercept=log10(1), 
              color = "red", 
              size = 0.05) + 
   labs(x = expression(log[10](prodbf_cov_iu)), 
       y = "Number of Studies (k)", 
       title = "log prodbf_cov_iu (es = 0.1, k = 2, Hi is false), covariance",
       subtitle = "Sample Size (n), Number of Studies (k) and Reliability (errorsd)",
       caption = "Red line: log(1) = 0, 1000 iterations", fill = "Error SD") +  
  theme_minimal()
```

### $Log_{10} \text{ } pBF_{iu}$, es = 0.1, k = 3, covariance
```{r, warning=F, echo = F}
# log pbf IU - covariance
# es = 0.1

# New facet label names for k variable
k.labs <- c("k = 2", "k = 3", "k = 10")
names(k.labs) <- c("2", "3", "10")

# New facet label names for n variable
n.labs <- c("n = 20", "n = 80", "n = 200", "n = 500")
names(n.labs) <- c("20", "80", "200", "500")

# New facet label names for error variable
errorsd.labs <- c("errorsd = 0", "errorsd = 0.5", "errorsd = 0.8")
names(errorsd.labs) <- c("0", "0.5", "0.8")

dat %>%
  filter(es == 0.1, k == 3) %>%
  ggplot(aes(x = log10(prodbf_cov_iu), y = factor(n), fill = factor(errorsd))) +
  stat_halfeye(
    adjust = 0.5,
    justification = -0.4,
    .width = 0,
    point_colour = NA, 
    alpha = 0.5
  ) +
  stat_dots(
    side = "left",
    justification = 1.3,
    binwidth = 0.1, 
    alpha=0.05, 
  ) +
  facet_wrap(~ factor(errorsd) , labeller = labeller(errorsd = errorsd.labs)) + 
   geom_vline(xintercept=log10(1), 
              color = "red", 
              size = 0.05) + 
   labs(x = expression(log[10](prodbf_cov_iu)), 
       y = "Number of Studies (k)", 
       title = "log prodbf_cov_iu (es = 0.1, k = 3, Hi is false), covariance",
       subtitle = "Sample Size (n), Number of Studies (k) and Reliability (errorsd)",
       caption = "Red line: log(1) = 0, 1000 iterations", fill = "Error SD") +  
  theme_minimal()
```

### $Log_{10} \text{ } pBF_{iu}$, es = 0.1, k = 10, covariance
```{r, warning=F, echo = F}
# log pbf IU - covariance
# es = 0.1

# New facet label names for k variable
k.labs <- c("k = 2", "k = 3", "k = 10")
names(k.labs) <- c("2", "3", "10")

# New facet label names for n variable
n.labs <- c("n = 20", "n = 80", "n = 200", "n = 500")
names(n.labs) <- c("20", "80", "200", "500")

# New facet label names for error variable
errorsd.labs <- c("errorsd = 0", "errorsd = 0.5", "errorsd = 0.8")
names(errorsd.labs) <- c("0", "0.5", "0.8")

dat %>%
  filter(es == 0.1, k == 10) %>%
  ggplot(aes(x = log10(prodbf_cov_iu), y = factor(n), fill = factor(errorsd))) +
  stat_halfeye(
    adjust = 0.5,
    justification = -0.4,
    .width = 0,
    point_colour = NA, 
    alpha = 0.5
  ) +
  stat_dots(
    side = "left",
    justification = 1.3,
    binwidth = 0.1, 
    alpha=0.05, 
  ) +
  facet_wrap(~ factor(errorsd) , labeller = labeller(errorsd = errorsd.labs)) + 
   geom_vline(xintercept=log10(1), 
              color = "red", 
              size = 0.05) + 
   labs(x = expression(log[10](prodbf_cov_iu)), 
       y = "Number of Studies (k)", 
       title = "log prodbf_cov_iu (es = 0.1, k = 10, Hi is false), covariance",
       subtitle = "Sample Size (n), Number of Studies (k) and Reliability (errorsd)",
       caption = "Red line: log(1) = 0, 1000 iterations", fill = "Error SD") +  
  theme_minimal()
```