---
title: "Plot distributions of raw estimates"
output: html_document
date: "2026-02-04"
---

```{r}
library(mvtnorm)
library(metafor)
library(data.table)

n       <- 500
k       <- 10
es      <- 0.1
errorsd <- 1
ndataset <- 1000

set.seed(6164900)
seeds <- sample(1:.Machine$integer.max, ndataset)

Sigma <- matrix(c(1, es, es, 1), 2, 2)

# get cor, cov and z for a specific condition
results <- lapply(seq_len(ndataset), function(i) {

  set.seed(seeds[i])

  dfs <- lapply(seq_len(k), function(j) {
    df <- rmvnorm(n, sigma = Sigma)
    noise <- matrix(rnorm(2 * n, sd = errorsd), ncol = 2)
    df + noise
  })

  cor_est <- sapply(dfs, function(x) cor(x)[2, 1])
  
  res_cor <- sapply(dfs, function(x) {
    r <- cor(x)[2, 1]
    se_r <- sqrt((1 - r^2) / (n - 2))
    c(r = r, se = se_r)
  })
  
  cov_est <- sapply(dfs, function(x) cov(x)[2, 1])

  res_cov <- sapply(dfs, function(x) {
    cov_xy <- cov(x)[2, 1]
    se_cov <- sqrt((var(x[,1]) * var(x[,2]) + cov_xy^2) / (n - 1))
    c(cov = cov_xy, se = se_cov)
  })
  
  z_est <- escalc(
    measure = "ZCOR",
    ri = cor_est,
    ni = rep(n * 2, k),
    append = FALSE
  )$yi
  
  res_beta <- sapply(dfs, function(x) {
    model <- lm(x[,2] ~ x[,1])
    beta_coef <- coef(model)[2]
    se_beta <- summary(model)$coefficients[2, 2]
    c(beta_coef, se_beta)
  })
  
  res_meandiff <- sapply(dfs, function(x) mean(x[,2]) - mean(x[,1]))
  
  res_abs_meandiff <- abs(res_meandiff)

  data.frame(
    replication = i,
    study       = seq_len(k),
    corest      = res_cor[1],
    cov         = cov_est,
    z           = z_est,
    beta        = res_beta[1],
    secor       = res_cor[2],
    sebeta      = res_beta[2],
    secov       = res_cov[2],
    meandiff = res_meandiff,
    abs_meandiff = res_abs_meandiff
  )
})

raw_estimates <- rbindlist(results)

raw_estimates[, `:=`(
  n = n,
  k = k,
  es = es,
  errorsd = errorsd
)]

raw_estimates
```

```{r}
library(ggplot2)

ggplot(raw_estimates, aes(cor)) +
  geom_density() +
  ggtitle("Sampling distribution of correlations")

ggplot(raw_estimates, aes(cov)) +
  geom_density() +
  ggtitle("Sampling distribution of covariances")

ggplot(raw_estimates, aes(z)) +
  geom_density() +
  ggtitle("Sampling distribution of z-scores")

ggplot(raw_estimates, aes(beta)) +
  geom_density() +
  ggtitle("Sampling distribution of beta")

ggplot(raw_estimates, aes(res_meandiff)) +
  geom_density() +
  ggtitle("Sampling distribution of mean diff")

ggplot(raw_estimates, aes(res_abs_meandiff)) +
  geom_density() +
  ggtitle("Sampling distribution of abs mean diff")
```


